### ISSUE TITLE
请问怎么使用？

### ISSUE THREAD

**Issue by easyboy3** [TonyTang1990/BehaviourTreeForLua#1]
请问怎么使用？我在一个prefab上挂上behaviorTree脚本，然后不知道怎么跟生成的树关联起来了，为了热更找你这个行为树了

**Comment by TonyTang1990** [comment]
不知道你问题解决没。不好意思，这个邮箱平时不怎么看，所以才看到你发的邮件。我写这个行为树，只支持通过TonyTnag->AI->行为树编辑器离线编辑生成行为树Json文件后，运行时加载使用的方式来使用。不像Behaviour
Designer可以直接挂了BehaviourTree之类的脚本后直接进行编辑。所以流程是1.
通过TonyTnag->AI->行为树编辑器离线编辑好一个行为树Json文件。2.运行时动态加载行为树Json文件使用。如果还有疑问，单独加我QQ(4358553363)咨询吧，加的时候说明加的原因。

**Comment by TonyTang1990** [comment]
QQ刚才打错了，应该是435853363

**Comment by TonyTang1990** [comment]
不知道你问题解决没。不好意思，这个邮箱平时不怎么看，所以才看到你发的邮件。我写这个行为树，只支持通过TonyTnag->AI->行为树编辑器离线编辑生成行为树Json文件后，运行时加载使用的方式来使用。不像Behaviour
Designer可以直接挂了BehaviourTree之类的脚本后直接进行编辑。所以流程是1.
通过TonyTnag->AI->行为树编辑器离线编辑好一个行为树Json文件。2.运行时动态加载行为树Json文件使用。

**Comment by TonyTang1990** [comment]
不知道你问题解决没。不好意思，没怎么关注Issues，所以才看到你发的Issues。我写这个行为树，只支持通过TonyTnag->AI->行为树编辑器离线编辑生成行为树Json文件后，运行时加载使用的方式来使用。不像Behaviour
Designer可以直接挂了BehaviourTree之类的脚本后直接进行编辑。所以流程是1.
通过TonyTnag->AI->行为树编辑器离线编辑好一个行为树Json文件。2.运行时动态加载行为树Json文件使用。

**Comment by easyboy3** [comment]
谢谢回复，后面主程又说用个纯lua的来搞方便热更我就找了个纯lua的，虽然有点问题。。你的行为树我还没看得很深入，能力有限，不过等我公司项目闲下来我会再看看的，反正先星了，谢谢你。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TonyTang1990/BehaviourTreeForLua"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TonyTang1990/BehaviourTreeForLua] 请问怎么使用？ (#1)





 
不知道你问题解决没。不好意思，没怎么关注Issues，所以才看到你发的Issues。我写这个行为树，只支持通过TonyTnag-&gt;AI-&gt;行为树编辑器离线编辑生成行为树Json文件后，运行时加载使用的方式来使用。不像Behaviour
 Designer可以直接挂了BehaviourTree之类的脚本后直接进行编辑。所以流程是1.
 通过TonyTnag-&gt;AI-&gt;行为树编辑器离线编辑好一个行为树Json文件。2.运行时动态加载行为树Json文件使用。

**Comment by TonyTang1990** [comment]
我这个虽然不是纯Lua的，但支持写Lua来扩展条件和行为节点(CS那方只需要添加Editor下的CS代码就能添加Lua的条件和行为节点编辑器支持了)。你说的纯Lua行为树是用的哪个？方便发个链接我也了解下吗？
